apps/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('home/', views.home),
    path('signup/', views.signup),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('new_quiz/', views.new_quiz),
    path('quiz/<int:quiz_id>/<int:question_num>', views.question_view, name='question'),
    path('quiz/<int:quiz_id>/add_question/<int:question_num>', views.add_question, name='add_question'),
    path('results/<int:quiz_id>', views.result, name='results'),
    path('delete/<int:quiz_id>', views.delete, name='delete'),
    path('signout/', views.signout),
]

quiz_app/urls.py
from django.urls import path,include

urlpatterns = [
    path('', include('apps.myapp.urls')),
]

apps/myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Quiz(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    num_of_quest = models.IntegerField(default=0)
    taken_by = models.IntegerField(default=0)
    highest_score = models.IntegerField(default=0)
    users= models.ManyToManyField(User, related_name='quizzes', through='Score')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

def __str__(self):
    return self.title

class Question(models.Model):
    question_text = models.TextField(max_length=255)
    question_num = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    def __str__(self):
        return self.question_text

class Score(models.Model):
    score = models.IntegerField()
    taken_on = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Choice(models.Model):
    choice_text = models.CharField(max_length=100)
    right_choice = models.BooleanField(default=False)
    question  = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

apps/myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)
    error_messages = {
        'password_mismatch': ("The two password fields didn't match."),
    }
    password1 = forms.CharField(
        label=("Password"),
        strip=False,
        widget=forms.PasswordInput,
    )
    password2 = forms.CharField(
        label=("Password confirmation"),
        widget=forms.PasswordInput,
        strip=False,
    )

    class Meta:
        model = User
        fields = (
            'username', 
            'first_name', 
            'last_name', 
            'email', 
            'password1', 
            'password2',
        )

    # def clean_password1(self, *args, **kwargs):
    #     password1 = self.cleaned_data.get("password1")
    #     if len(password1)<8:
    #             raise forms.ValidationError("The password must be at least 8 characters long ")  
    #     else:
    #         return password1
    
    def clean_password2(self, *args, **kwargs):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(SignUpForm,self).save(commit=False)
        user.first_name=self.cleaned_data['first_name']
        user.last_name=self.cleaned_data['last_name']
        user.email=self.cleaned_data['email']

        if commit:
            user.save()

        return user

apps/myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import (logout,login, authenticate)
from django.utils import timezone
from .models import *
from .forms import *
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.
score = 0

def index(request):
    return render(request,'myapp/index.html')

def home(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
    if request.method == "POST":
        username = request.POST['username']
        r_password = request.POST['password1']
        user = authenticate(request, username = username, password = r_password)
        if user:
            login(request, user)
        if request.user.is_authenticated:
            return redirect('dashboard')
        else:
            messages.warning(request, 'Incorrect Login Details')
            return render(request, 'myapp/home.html',{})
    else:
        return render(request, 'myapp/home.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            if not (User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists()):
                User.objects.create_user(username, first_name, last_name, email, password1)
            user = form.save()
            login(request, user)
            raise forms.ValidationError('A username with that email or password already exists')
            return redirect('dashboard')
    else:
        form = SignUpForm()
    return render(request, 'myapp/register.html', {'form': form})

def dashboard(request):
    all_quizzes = Quiz.objects.all().order_by('-created_at')
    if request.user.is_authenticated:
        taken_quizzes = request.user.score_set.all().order_by('-taken_on')
        my_quizzes = request.user.quiz_set.all()
    else:
        taken_quizzes = {}
        my_quizzes = {}
    return render(request, 'myapp/dashboard.html', {'all_quizzes' : all_quizzes, 'taken_quizzes':taken_quizzes, 'my_quizzes' : my_quizzes})

@login_required(login_url='/')
def new_quiz(request):
    if request.method == "POST":
        date_created = timezone.now()
        author = request.user
        quiz_name = request.POST['title']
        if quiz_name == '':
            return render(request, 'new_quiz', {'error_message' : "Quiz name can't be blank"})
        quiz = Quiz.objects.create(created_at=date_created, author=author, title=quiz_name)
        quiz.save()
        return redirect('add_question', quiz_id=quiz.id, question_num=1)
    else:
        return render(request, 'myapp/add_quiz.html', {})

def add_question(request, quiz_id, question_num):
    error_message=""
    if request.method == "POST":
        if request.POST['question_text']=='':
            context = {'title': Quiz.objects.get(id=quiz_id).title, 'quest_no' : question_num, 'error_message' : "Question text can't be blank"}
            return render(request, 'myapp/add_question.html', context)
        elif request.POST['choice1'] == '' or request.POST['choice2']=='' or request.POST['choice3']=='' or request.POST['choice4']=='':
            context = {'title': Quiz.objects.get(id=quiz_id).title, 'ques_no' : question_num, 'error_message' : "Please fill all the choices"}
            return render(request, 'myapp/add_question.html', context)
        else:
            quiz = get_object_or_404(Quiz, id=quiz_id)
            question_text = request.POST['question_text']
            q = Question.objects.create(quiz=quiz, question_text=question_text, question_num=question_num)
            choice1 = Choice(question = q, choice_text = request.POST['choice1'])
            choice2 = Choice(question = q, choice_text = request.POST['choice2'])
            choice3 = Choice(question = q, choice_text = request.POST['choice3'])
            choice4 = Choice(question = q, choice_text = request.POST['choice4'])
            try:
                r_choice = request.POST['choice']
                if r_choice == 'choice1':
                    choice1.right_choice = True
                elif r_choice == 'choice2':
                    choice2.right_choice = True
                elif r_choice == 'choice3':
                    choice3.right_choice = True
                elif r_choice == 'choice4':
                    choice4.right_choice = True
            except MultiValueDictKeyError:
                q.delete()
                error_message = "Please mark the correct answer"
                context =  {'quiz_name': Quiz.objects.get(id=quiz_id).title, 'ques_no' : question_num, "error_message" : error_message}
                return render(request, 'myapp/add_question.html', context)

            quiz.num_of_quest = question_num
            quiz.save()
            choice1.save()
            choice2.save()
            choice3.save()
            choice4.save()

            #button dependant behaviour
            if '_save&add' in request.POST:
                return redirect('add_question', quiz_id=quiz_id, question_num=question_num+1)
            else:
                return redirect('dashboard')
    else:
        context =  {'quiz_name': Quiz.objects.get(id=quiz_id).title, 'ques_no' : question_num}
        return render(request, 'myapp/add_question.html', context)

@login_required(login_url='/')
def question_view(request, quiz_id, question_num):
    global score
    quiz = get_object_or_404(Quiz, id=quiz_id)
    if question_num == len(quiz.question_set.all())+1:
        quiz.taken_by += 1
        if score > quiz.highest_score:
            quiz.highest_score = score
        quiz.save()
        sc = str(score)
        s = Score.objects.create(score=score, user=request.user, quiz=quiz, taken_on=timezone.now())
        s.save()
        score = 0
        return render(request, 'myapp/score.html', {"score" : sc})
    ques = quiz.question_set.all()[question_num-1]
    done_p = int(100*question_num/len(quiz.question_set.all()))
    if request.method == "POST":
        if '_skip' in request.POST:
            return redirect('question', quiz_id=quiz_id, question_num=question_num+1)
        else:
            try:
                selected_choice = Choice.objects.get(id = request.POST["choices"])
                if selected_choice.right_choice == True:
                    score += 1
            except MultiValueDictKeyError:
                context = {'quiz' : quiz, 'ques' : ques, 'done_p' : done_p}
                messages.warning(request, "Please select a choice")
                return render(request, 'myapp/question_view.html', context)
            return redirect('question', quiz_id=quiz_id, question_num=question_num+1)
    context = {'quiz' : quiz, 'ques' : ques, 'done_p' : done_p}
    return render(request, 'myapp/question_view.html', context)

def result(request, quiz_id):
    quiz = get_object_or_404(Quiz, id=quiz_id)
    if quiz.author != request.user:
        messages.warning(request, "You can't view the results. Only author can do that")
        return redirect('dashboard')
    else:
        quiz = get_object_or_404(Quiz, id=quiz_id)
        scores = quiz.score_set.all().order_by('score')
        return render(request, 'myapp/results.html', {'quiz':quiz, 'scores': scores})

def delete(request, quiz_id):
    q = Quiz.objects.get(id=quiz_id)
    if q.author == request.user:
        q.delete()
        messages.success(request, "Quiz deleted")
    else:
        messages.warning(request, "Can't delete the quiz. Rights reserved with the author")
    return redirect('dashboard')

def signout(request):
    logout(request)
    return redirect('/home')

apps/myapp/templates/myapp/add_question.html
{% extends 'myapp/index.html' %}

{% block content %}
{% if error_message %}
<div class="alert alert-danger">
{{ error_message }}
</div>
{% endif %}
<h1 style="text-align: center"><span class="badge badge-pill badge-secondary">{{ title }}</span></h1>
<form method = "POST" class="post-form">
  {% csrf_token %}
  <label for="q">Question No: {{ question_num }}</label>
  <input class="form-control" id="q" type="text" name="question_text" placeholder="Type Question Here">
  <br>
  <table class="table">
  <thead>
    <tr>
      <th>Choice</th>
      <th>Correct?</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <input class="form-control" type="text" name="choice1" placeholder="Choice 1 Here">
      </td>
      <td>
        <input type="radio" name="choice" value="choice1">
      </td>
    </tr>
    <tr>
      <td>
        <input class="form-control" type="text" name="choice2" placeholder="Choice 2 Here">
      </td>
      <td>
        <input type="radio" name="choice" value="choice2">
      </td>
    </tr>
    <tr>
      <td>
        <input class="form-control" type="text" name="choice3" placeholder="Choice 3 Here">
      </td>
      <td>
        <input type="radio" name="choice" value="choice3">
      </td>
    </tr>
    <tr>
      <td>
        <input class="form-control" type="text" name="choice4" placeholder="Choice 4 Here">
      </td>
      <td>
        <input type="radio" name="choice" value="choice4">
      </td>
    </tr>
  </tbody>
</table>
  <br><button type="submit" name="_save&add" class="btn btn-primary">Save & add another</button>
  <button style="float:right" type="submit" name="_save" class="btn btn-primary">Save Quiz</button>
</form>
<br>
{% endblock %}

apps/myapp/templates/myapp/add_quiz.html
{% extends 'myapp/index.html' %}

{% block content %}
	{% if error_message %}
	<div class="alert alert-danger">
	{{ error_message }}
	</div>
	{% endif %}
  <form method = "POST" class="post-form">
    {% csrf_token %}
    <label for="title">Enter quiz name:</label>
    <input class="form-control" type="text" name="title" id="title">
    <br><button type="submit" class="btn btn-primary">
      Submit
    </button>
  </form>
{% endblock %}

apps/myapp/templates/myapp/dashboard.html
{% extends 'myapp/index.html' %}

{% block content %}
{% if messages %}
{% for message in messages %}
  <div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endfor %}
{% endif %}
<a style="float:right" href="/new_quiz">
  <button class="btn btn-primary">Create Quiz</button>
</a>
<h1> Dashboard </h1>
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">All Quizzes</a>
  </li>
  <li>
    {% if request.user.is_authenticated %}
    <a class="nav-link" id="taken-tab" data-toggle="tab" href="#taken" role="tab" aria-controls="taken" aria-selected="false">Taken</a>
    {% else %}
    <a class="nav-link disabled" id="taken-tab" data-toggle="tab" href="#taken" role="tab" aria-controls="taken" aria-selected="false">Taken</a>
    {% endif %}
  </li>
  <li>
    {% if request.user.is_authenticated %}
    <a class="nav-link " id="myquizzes-tab" data-toggle="tab" href="#myquizzes" role="tab" aria-controls="myquizzes" aria-selected="false">Quizzes by me</a>
    {% else %}
    <a class="nav-link disabled" id="myquizzes-tab" data-toggle="tab" href="#myquizzes" role="tab" aria-controls="myquizzes" aria-selected="false">Quizzes by me</a>
    {% endif %}
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    <table class="table table-hover">
      <thead class="thead-inverse">
       <tr>
         <th>Quiz</th>
         <th>Author</th>
         <th>Questions</th>
         <th>Taken By</th>
         <th></th><th></th>
       </tr>
      </thead>
      <tbody>
        {% for quiz in all_quizzes %}
        <tr>
          <td>{{ quiz.title }}<br>
          <small class="text-muted d-block">{{ quiz.created_at|date:"d M, Y \a\t G:i" }}</small></td>
          <td class="align-middle">{{ quiz.author.first_name }}</td>
          <td class="align-middle">{{ quiz.num_of_quest }}</td>
          <td class="align-middle">{{ quiz.taken_by }}</td>
          <td class="align-middle"><a href="{% url 'question' quiz.id 1 %}"><button class="btn btn-success">Take Quiz</button></a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="tab-pane fade show" id="taken" role="tabpanel" aria-labelledby="taken-tab">
    <table class="table">
      <thead>
        <th>Quiz</th>
        <th>Author</th>
        <th>Taken On</th>
        <th>Score</th>
      </thead>
      <tbody>
          {% for q in taken_quizzes %}
          <tr>
            <td>{{ q.quiz }}</td>
            <td>{{ q.quiz.author.first_name }}</td>
            <td>{{ q.taken_on }}</td>
            <td>{{ q.score }} / {{ q.quiz.num_of_quest }}</td>
          </tr>
          {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="tab-pane fade show" id="myquizzes" role="tabpanel" aria-labelledby="myquizzes-tab">
    <table class="table table-hover">
      <thead class="thead-inverse">
       <tr>
         <th>Quiz</th>
         <th>Questions</th>
         <th>Taken By</th>
         <th>Highest Score</th>
         <th></th>
         <th></th>
       </tr>
      </thead>
      <tbody>
        {% for quiz in my_quizzes %}
        <tr>
          <td>{{ quiz.title }}<br>
          <small class="text-muted d-block">{{ quiz.created_at|date:"d M, Y \a\t G:i" }}</small></td>
          <td class="align-middle">{{ quiz.num_of_quest }}</td>
          <td class="align-middle">{{ quiz.taken_by }}</td>
          <td class="align-middle">{{ quiz.highest_score }}</td>
          <td class="align-middle"><a href="{% url 'delete' quiz.id %}"><button type="button" class="btn btn-danger">Delete quiz</button></a></td>
          <td class="align-middle"><a href="{% url 'results' quiz.id %}"><button type="button" class="btn btn-info">View Results</button></a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

apps/myapp/templates/myapp/home.html
{% extends 'myapp/index.html' %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endfor %}
{% endif %} <h2> Login </h2>
  <br>
  <form method = "POST"> {% csrf_token %}
    <div class="form-group">
      <label for="usr">Username: </label>
    <input type="text" class="form-control" name="username" id="usr">
  </div>
    <div class="form-group">
    <label for="pwd">Password: </label>
    <input type="password" class="form-control" name="password1" id="pwd">
  </div>
    <button type="submit" class="btn btn-default">Login</button>
  </form>
  <div class="border-top pt-3">
    <div class="text-center text-muted">Don't have an account?
      <a href="/signup"><button class="btn btn-danger">Create an account</button></a>
    </div>
  </div>
{% endblock content%}

apps/myapp/templates/myapp/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,500" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
	<body style=" background-color: rgb(56, 59, 224);">
	<nav class="navbar navbar-expand-sm navbar bg-dark fixed-top">
		<div class="container">
		<a class="navbar-brand" href="/home">Let's Quiz!!</a>
			<ul class="navbar-nav">
				<li class="nav-item">
						 {% if request.user.is_authenticated %}
							<a style="color:white" class="nav-link">Logged in as {{ user }}</a>
						{% endif %}
				</li>
			    <li class="nav-item">
						{% if request.user.is_authenticated %}
							<a href="/signout" class="nav-link">Logout</a>
						{% else %}
							<a class="nav-link" href="/home">Login</a>
						{% endif %}
				</li>
			</ul>
		</div>
	</nav>
	<div class="container" style="font-family: 'Roboto', sans-serif;margin-top:100px;padding:19px; background-color: white; border-radius: 15px;">
	  {% block content %}
	  {% endblock %}
	</div>
  </body>
</html>
                                                                                       

apps/myapp/templates/myapp/question_view.html
{% extends 'myapp/index.html' %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endfor %}
{% endif %}
<div class="progress">
  <div class="progress-bar" style="width:{{ done_p }}%"></div>
</div>
<h1 style="text-align: center"><span class="badge badge-pill badge-secondary">{{ quiz.title }}</span></h1>
<hr>
  <h2>{{ques.question_text }}</h2><br>
  <form method="POST"> {% csrf_token %}
    {% for choice in ques.choice_set.all %}
    <h5><input type="radio" name="choices" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label class="form-check-label" for="choice{{ forloop.counter }}">
      {{ choice.choice_text }}
    </label></h5>
    {% endfor %}<br>
    <button type="submit" class="btn btn-success">Submit</button>
    <button style="float:right;" type="submit" name="_skip" class="btn btn-success">Skip</button>
  </form>
{% endblock %}

apps/myapp/templates/myapp/register.html
{% extends 'myapp/index.html' %}

{% block content %}
  {{ error_message }}
  <form method="POST" class="post-form">
    {% csrf_token %}
    <h1>Register</h1>
    <table>{{ form.as_table}}</table>
    <button type="submit" class="btn btn-primary">SignUp</button>
  <hr>
  </form>
  <div class="text-center text-muted">Already have an account?
    <a href="/home"><button class="btn btn-danger">SignIn</button></a>
  </div>
{% endblock %}

apps/myapp/templates/myapp/results.html
{% extends 'myapp/index.html'%}

{% block content %}
<a href="{% url 'dashboard' %}">Go to Dashboard</a><hr>
<h2>Results for Quiz : <span class="badge badge-pill badge-secondary">{{ quiz.title }}</span></h2>
<br>
<table class="table">
  <thead>
    <th>User</th>
    <th>Taken On</th>
    <th>Score</th>
   </thead>
   <tbody>
   	{% for score in scores %}
   	   	<tr>
	   		<td>{{ score.user.first_name }}</td>
	   		<td>{{  score.taken_on }}</td>
	   		<td>{{ score.score }} / {{ score.quiz.num_of_quest }}</td>
   		</tr>
   	{% endfor %}
   </tbody>
{% endblock %}

apps/myapp/templates/myapp/score.html
{% extends 'myapp/index.html' %}

{% block content %}
  <div class="alert alert-success">
    Your score is {{ score }}
  </div>
  <a href="{% url 'dashboard' %}">Go to Dashboard</a>
{% endblock %}